" Loads pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim

" Pathogen set up
filetype off
call pathogen#infect()
call pathogen#infect("unpublished/{}")
call pathogen#helptags()
filetype plugin indent on

source $HOME/.vim/vimrc_settings
source $HOME/.vim/vimrc_functions
source $HOME/.vim/vimrc_commands
source $HOME/.vim/vimrc_mappings
source $HOME/.vim/vimrc_autocmds

if &loadplugins
  set rtp+=/usr/local/opt/fzf
  source $HOME/.vim/vimrc_plugins
endif
